--- 

- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  pre_tasks:
  - name: update repo
    apt:
        update_cache: yes
    changed_when: False
  
  tasks:
  - name: install npm package globally.
    npm: name=npm global=yes
  - name: install redux-thunk package globally.
    npm: name=redux-thunk global=yes
  - name: install shave package globally.
    become: true
    npm: name=shave global=yes
  - include: packages_debian/users.yml  
  - include: packages_debian/kali_apt.yml   
  - include: packages_debian/kali_python.yml    
  - include: packages_debian/kali_docker.yml   
  - include: packages_debian/cron.yml     

        
