--- 
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    string_conversion_action: ignore
    
  pre_tasks:
  - name: update repo
    apt:
        update_cache: yes
    changed_when: False
  
  tasks:
  - include: packages_debian/users.yml  
  - include: packages_debian/kali_apt.yml   
  - include: packages_debian/kali_python.yml    
  - include: packages_debian/kali_docker.yml   
  - include: packages_debian/kali_node.yml   
  - include: packages_debian/kali_ruby.yml   
  - include: packages_debian/zsh_setup.yml   
  - include: packages_debian/cron.yml     

        
