--- 
- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    string_conversion_action: ignore
    
  pre_tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_hostname }}"
    - "{{ ansible_fqdn }}"
    - "{{ ansible_distribution_major_version }}"

  
  tasks:
  - name: update repo
    package:
        update_cache: yes
    changed_when: False
    
  - name: Creates nfs directory on desktop
    file:
      path: /home/nnnn/Desktop/nfs/
      state: directory   
      
  - name: Mount local NFS volume
    mount:
      src: 192.168.4.85:/storage
      path: /mnt/shared_data
      opts: rw,sync,hard,intr
      state: mounted
      fstype: nfs
      
  - name: install kali tools for kali linux
    package: name=htop state=latest
    when: ansible_facts['distribution'] == "Kali GNU/Linux"
    
  - include: packages_debian/users.yml  
  - include: packages_debian/kali_package.yml   
  - include: packages_debian/kali_python.yml    
  - include: packages_debian/kali_docker.yml   
  - include: packages_debian/kali_node.yml   
  - include: packages_debian/kali_ruby.yml   
  - include: packages_debian/zsh_setup.yml   
  - include: packages_debian/cron.yml     

        
