--- 

- hosts: localhost
  connection: local
  gather_facts: false
  become: true

  pre_tasks:
  - name: update repo
    apt:
        update_cache: yes
    changed_when: False
  
  tasks:
  - include: packages_debian/kali.yml   

        
