--- 
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    string_conversion_action: ignore

  tasks:

  - name: install ruby gems
    become: false
    gem: name={{ item }} 
    with_items: ruby_gems
    loop:
    - vagrant
    - rake
    - colorls


  - debug: msg="{{ lookup('env','HOME') }   }"

  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: What is your password?

  tasks:

    - name: Print a message
      ansible.builtin.debug:
        msg: 'Logging in as {{ username }}'




