--- 
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    string_conversion_action: ignore
  tasks:
  - debug: msg="{{ lookup('env','HOME') }}"




